platform:
  - 'platform/**'

kubernetes:
  - '**/deployment.yaml'
  - '**/service.yaml'
  - '**/namespace.yaml'
  - '**/kustomization.yaml'

ci-cd:
  - '.github/workflows/**'
  - 'azure-pipelines.yml'

docs:
  - '**/*.md'
  - 'docs/**'

application:
  - 'app/**'